name: Defect
description: Create a defect report
assignees: []
labels:
  - defect
  - needs-grooming
projects:
  - insilica/12
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the defect
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any other context, screenshots, or information that might be helpful
      placeholder: Logs, screenshots, related issues, etc.
    validations:
      required: false
