#!/usr/bin/env python3

from pathlib import Path

def generate_endpoint_imports():
    script_dir = Path(__file__).parent
    api_path = script_dir / "gen" / "api"

    if not api_path.exists():
        raise FileNotFoundError(f"API directory not found: {api_path}")

    imports_by_category = {}

    for category_dir in sorted(api_path.iterdir()):
        if not category_dir.is_dir() or category_dir.name.startswith("_"):
            continue

        category_name = category_dir.name
        modules = []

        for py_file in sorted(category_dir.glob("*.py")):
            if py_file.stem != "__init__":
                modules.append(py_file.stem)

        if modules:
            imports_by_category[category_name] = modules

    return imports_by_category


def format_category_name(category: str) -> str:
    return " ".join(word.capitalize() for word in category.split("_"))


def generate_init_file_content(imports_by_category: dict) -> str:
    lines = [
        '"""',
        'The API endpoint imports are auto-generated by update_exports.py.',
        'Run this script after regenerating the OpenAPI client to update imports.',
        '"""',
        '',
        'from .gen.client import AuthenticatedClient, Client',
        '',
        'from .gen.models import *',
        'from .gen.errors import *',
        'from .gen.types import *',
        '',
    ]

    # Add imports for each category
    for category, modules in imports_by_category.items():
        for module in modules:
            lines.append(f'from .gen.api.{category} import {module}')
        lines.append('')

    lines.extend([
        '__all__ = [name for name in globals() if not name.startswith("_")]',
        '',
    ])

    return '\n'.join(lines)


def main():
    print("Scanning API endpoints...")
    imports_by_category = generate_endpoint_imports()

    total_endpoints = sum(len(modules) for modules in imports_by_category.values())
    print(f"Found {len(imports_by_category)} categories with {total_endpoints} endpoints:")
    for category, modules in imports_by_category.items():
        print(f"   - {category}: {len(modules)} endpoints")

    print("\nGenerating __init__.py content...")
    content = generate_init_file_content(imports_by_category)
    script_dir = Path(__file__).parent
    init_file = script_dir / "__init__.py"

    print(f"Writing to {init_file.relative_to(script_dir.parent.parent.parent)}...")
    init_file.write_text(content, encoding='utf-8')

    print("Done! The spec component's __init__.py has been updated.")

if __name__ == "__main__":
    main()